import SwiftUI

/// Legal Disclaimer Screen — user MUST agree before using the app.
/// Protects against liability. Checkbox required before proceeding.
/// Shows only once on first launch (persisted via @AppStorage).
struct DisclaimerView: View {
    @Binding var hasAgreed: Bool
    @State private var checkboxChecked = false
    @State private var showError = false

    var body: some View {
        ZStack {
            // Background
            LinearGradient(
                colors: [
                    Color(red: 0.08, green: 0.06, blue: 0.14),
                    Color(red: 0.12, green: 0.08, blue: 0.18)
                ],
                startPoint: .top,
                endPoint: .bottom
            )
            .ignoresSafeArea()

            ScrollView {
                VStack(spacing: 24) {
                    Spacer(minLength: 40)

                    // Header
                    VStack(spacing: 12) {
                        Image(systemName: "shield.checkered")
                            .font(.system(size: 44))
                            .foregroundColor(Color(red: 0.9, green: 0.7, blue: 0.3))

                        Text("Important Disclaimer")
                            .font(.system(size: 26, weight: .bold, design: .serif))
                            .foregroundColor(.white)

                        Text("Please read carefully before continuing")
                            .font(.system(size: 14, weight: .medium))
                            .foregroundColor(.white.opacity(0.6))
                    }

                    // Disclaimer text
                    VStack(alignment: .leading, spacing: 16) {
                        disclaimerSection(
                            title: "Not a Medical Service",
                            text: "SoulSpeak is a wellness and self-reflection app designed for entertainment and general wellness purposes ONLY. It is NOT a substitute for professional medical advice, diagnosis, or treatment."
                        )

                        disclaimerSection(
                            title: "Fictional Characters",
                            text: "\"Dr. Hope\" and \"Mr. Hope\" are fictional AI-generated characters. They are NOT real licensed medical doctors, therapists, counselors, psychologists, or mental health professionals. No doctor-patient or therapist-client relationship is created by using this app."
                        )

                        disclaimerSection(
                            title: "No Professional Advice",
                            text: "Any responses, suggestions, or conversations provided by this app are generated by artificial intelligence and should NOT be considered professional medical, psychological, therapeutic, or counseling advice."
                        )

                        disclaimerSection(
                            title: "Seek Professional Help",
                            text: "If you are experiencing a mental health crisis, suicidal thoughts, or any medical emergency, please immediately contact 911, the 988 Suicide & Crisis Lifeline, or your local emergency services. Do NOT rely on this app for crisis support."
                        )

                        disclaimerSection(
                            title: "Use at Your Own Risk",
                            text: "By using SoulSpeak, you acknowledge that you use this app at your own risk. The creators, developers, and operators of SoulSpeak shall not be held liable for any damages, harm, or adverse effects resulting from the use of this application."
                        )

                        disclaimerSection(
                            title: "No Guarantee of Results",
                            text: "SoulSpeak makes no guarantees regarding outcomes, improvements in mental health, or any specific results from using this app. Individual experiences may vary."
                        )

                        disclaimerSection(
                            title: "Data & Privacy",
                            text: "Your voice recordings, journal entries, and mood data are stored locally on your device. SoulSpeak is not responsible for any data loss. AI conversation data may be processed through third-party APIs subject to their respective privacy policies."
                        )
                    }
                    .padding(20)
                    .background(
                        RoundedRectangle(cornerRadius: 16)
                            .fill(Color.white.opacity(0.05))
                            .overlay(
                                RoundedRectangle(cornerRadius: 16)
                                    .stroke(Color.white.opacity(0.1), lineWidth: 1)
                            )
                    )

                    // Checkbox agreement
                    Button(action: {
                        withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                            checkboxChecked.toggle()
                            showError = false
                        }
                    }) {
                        HStack(alignment: .top, spacing: 14) {
                            // Checkbox
                            ZStack {
                                RoundedRectangle(cornerRadius: 6)
                                    .stroke(checkboxChecked ? Color(red: 0.9, green: 0.7, blue: 0.3) : Color.white.opacity(0.4), lineWidth: 2)
                                    .frame(width: 26, height: 26)

                                if checkboxChecked {
                                    RoundedRectangle(cornerRadius: 6)
                                        .fill(Color(red: 0.9, green: 0.7, blue: 0.3))
                                        .frame(width: 26, height: 26)

                                    Image(systemName: "checkmark")
                                        .font(.system(size: 14, weight: .bold))
                                        .foregroundColor(.black)
                                }
                            }

                            // Agreement text
                            Text("I have read, understand, and agree to this disclaimer. I acknowledge that SoulSpeak does NOT provide real medical, therapeutic, or counseling services, and that \"Dr. Hope\" and \"Mr. Hope\" are fictional AI characters — NOT real healthcare professionals.")
                                .font(.system(size: 13, weight: .medium))
                                .foregroundColor(.white.opacity(0.85))
                                .multilineTextAlignment(.leading)
                                .lineSpacing(3)
                        }
                    }
                    .padding(.top, 8)

                    // Error message if they try to proceed without checking
                    if showError {
                        HStack(spacing: 6) {
                            Image(systemName: "exclamationmark.triangle.fill")
                                .font(.system(size: 12))
                            Text("You must agree to the disclaimer to continue")
                                .font(.system(size: 12, weight: .medium))
                        }
                        .foregroundColor(.red)
                        .transition(.opacity)
                    }

                    // Continue button
                    Button(action: {
                        if checkboxChecked {
                            withAnimation(.easeInOut(duration: 0.3)) {
                                hasAgreed = true
                            }
                        } else {
                            withAnimation(.spring(response: 0.3)) {
                                showError = true
                            }
                        }
                    }) {
                        Text("I Agree — Continue to SoulSpeak")
                            .font(.system(size: 16, weight: .bold))
                            .foregroundColor(checkboxChecked ? .white : .white.opacity(0.4))
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 18)
                            .background(
                                RoundedRectangle(cornerRadius: 14)
                                    .fill(checkboxChecked
                                          ? LinearGradient(colors: [Color(red: 0.7, green: 0.4, blue: 0.8), Color(red: 0.5, green: 0.25, blue: 0.7)], startPoint: .leading, endPoint: .trailing)
                                          : LinearGradient(colors: [Color.white.opacity(0.1), Color.white.opacity(0.05)], startPoint: .leading, endPoint: .trailing)
                                    )
                            )
                    }
                    .padding(.top, 8)

                    // Legal footer
                    Text("Last updated: July 2026 | Version 1.0")
                        .font(.system(size: 10))
                        .foregroundColor(.white.opacity(0.3))
                        .padding(.bottom, 30)
                }
                .padding(.horizontal, 24)
            }
        }
    }

    // MARK: - Disclaimer Section
    private func disclaimerSection(title: String, text: String) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack(spacing: 8) {
                Circle()
                    .fill(Color(red: 0.9, green: 0.7, blue: 0.3))
                    .frame(width: 6, height: 6)
                Text(title)
                    .font(.system(size: 14, weight: .bold))
                    .foregroundColor(.white)
            }

            Text(text)
                .font(.system(size: 12, weight: .regular))
                .foregroundColor(.white.opacity(0.75))
                .lineSpacing(3)
        }
    }
}
